runtime: python37
service: default

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /index\.html
  static_files: index.html
  upload: index\.html

- url: /
  static_files: index.html
  upload: index\.html

- url: /cal
  static_files: index.html
  upload: index\.html

- url: /static
  static_dir: static

- url: /img
  static_dir: img